<?php

namespace App\Http\Controllers;

use App\Models\AttendanceRecord;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Http\JsonResponse;

class AttendanceController extends Controller
{
    public function scan(Request $request): JsonResponse
    {
        $data = $request->validate([
            'schedule_session_id'=>'required|exists:schedule_sessions,id',
            'student_nis'=>'required|exists:students,nis',
            'attendance_date'=>'required|date',
        ]);

        $session = \App\Models\ScheduleSession::find($data['schedule_session_id']);
        $student = \App\Models\Student::where('nis', $data['student_nis'])->first();

        if ($session->classroom_id != $student->classroom_id) {
            return response()->json([
                'message' => 'Siswa tidak terdaftar di kelas ini!',
                'student_class' => $student->classroom_id,
                'session_class' => $session->classroom_id
            ], 422);
        }

        $journal = \App\Models\TeachingJournal::firstOrCreate(
            [
                'schedule_session_id' => $session->id,
                'journal_date' => $data['attendance_date']
            ],
            [
                'topic' => '-',
                'observation_notes' => 'Generated by QR Scan',
                'location' => $session->classroom->name ?? 'Classroom',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        );

        $rec = AttendanceRecord::updateOrCreate(
            [
                'teaching_journal_id' => $journal->id,
                'student_nis' => $data['student_nis']
            ],
            [
              'status'=>'Hadir',
              'notes' => 'Scan QR ' . now()->format('H:i')
            ]
        );

        return response()->json($rec, 201);
    }

    public function manual(Request $request): JsonResponse
    {
        $data = $request->validate([
            'schedule_session_id'=>'required|exists:schedule_sessions,id',
            'student_nis'=>'required|exists:students,nis',
            'attendance_date'=>'required|date',
            'status'=>'required|in:Hadir,Sakit,Izin,Alpa,Belum Tercatat'
        ]);

        $session = \App\Models\ScheduleSession::find($data['schedule_session_id']);
        $student = \App\Models\Student::where('nis', $data['student_nis'])->first();
        if ($session->classroom_id != $student->classroom_id) {
            return response()->json(['message' => 'Siswa tidak terdaftar di kelas ini'], 422);
        }

        $journal = \App\Models\TeachingJournal::firstOrCreate(
            ['schedule_session_id' => $session->id, 'journal_date' => $data['attendance_date']],
            ['topic' => '-', 'observation_notes' => 'Generated by Manual Input', 'location' => $session->classroom->name, 'created_at' => now()]
        );

        $rec = AttendanceRecord::updateOrCreate(
            ['teaching_journal_id' => $journal->id, 'student_nis' => $data['student_nis']],
            [
              'status'=>$data['status'],
              'notes'=>'Manual Input'
            ]
        );

        return response()->json($rec, 201);
    }

    public function status(Request $request): JsonResponse
    {
        $data = $request->validate([
            'schedule_session_id'=>'required|exists:schedule_sessions,id',
            'student_nis'=>'required|exists:students,nis',
            'attendance_date'=>'required|date',
            'status'=>'required|in:Hadir,Sakit,Izin,Alpa,Belum Tercatat'
        ]);

        $session = \App\Models\ScheduleSession::find($data['schedule_session_id']);
        
        $journal = \App\Models\TeachingJournal::firstOrCreate(
            ['schedule_session_id' => $session->id, 'journal_date' => $data['attendance_date']],
            ['topic' => '-', 'observation_notes' => 'Generated by Status Input', 'location' => $session->classroom->name ?? '-', 'created_at' => now()]
        );

        $rec = AttendanceRecord::updateOrCreate(
            ['teaching_journal_id' => $journal->id, 'student_nis' => $data['student_nis']],
            [
              'status'=>$data['status'],
              'notes' => 'Status Update'
            ]
        );

        return response()->json($rec);
    }

    public function recap(Request $request): JsonResponse
    {
        $q = AttendanceRecord::query();

        if($request->filled('classroom_id')){
            $classroomId = (int) $request->input('classroom_id');
            $q->whereHas('session', function($s) use ($classroomId){
                $s->where('classroom_id', $classroomId);
            });
        }
        if($request->filled('date_from')) $q->whereDate('attendance_date','>=',$request->date('date_from'));
        if($request->filled('date_to'))   $q->whereDate('attendance_date','<=',$request->date('date_to'));

        return response()->json($q->paginate(50));
    }
}
